language: node_js
node_js:
  - 14
before_install:
  - npm i -g npm@6.14.7
env:
  - PORT=8000
deploy:
  provider: heroku
  api_key:
    secure: LCs6gJOIbQBzwBIFj8EEBg5hz0qyrfsFDy+g3AKeWwi+zo2zPEAcmbqKozu+B3ZxnP3kZHlnlUOU5m7lL9vSVHD0g1WaMUsZvgI1ooI8FVnT02UZBx65dqif3Vzd3BYMBYWl0LbnKdRspQmoHS9G9eUI/mf19fO1ndx5dCQxmG2C5Z8b3o3dlVmAcKNwRnc38H30H79JObKPlN6z6ozthudBkFzicjp9T6u2IhXdygMTzZOiyR0CXrGv6mla6w/bkzITbdEx4AmKAlZk1SwfmfRvhZ7tnIdsJsUMfhM9+IQXWnLr91+JpEs+zb0Hlb2D4U6KH8ioBWqCkS6hjWev31ZgUAMb7jb4yxhOZQy5swWOUrd2R4ip8NiyZJ5b4hBFRDw+ZCx/SsMRxn7DC18GHZUSaMFhJiNUvAyWmfoFnHbKy8xDTDvvLsYOLQTAvnsR7AfU5v60q4DElxqudYnppzEAdN7+wkH8nnHpPmOoaJnWv107iUB9MUuFQLfr9XNb4VeuexyL+lL16KosQdWpCn7IOFq3VoaSqu70R9JWG7T36FKaGgafcSMnUd7aQzYNScxFzXXvuGYjYCXK1obkwDAAu8qzImJUcbeolHBI8o/oXS2grM1BCvQJj/JQDEtnMB8DyMYYXRCFaowTMJ5kZ4FIvvVJFYpC6xRoFVsfZUM=
